services:
  admin-2:
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: always
    restart: always
    environment:
      SHM_HOST: https://admin.myvpn24.ru
      VITE_SHOW_SWAGGER: "true"
      SHM_BASE_PATH: /
    ports:
      - "8080:80"
